### ISSUE TITLE
Android is unable to build

### ISSUE THREAD

**Issue by bulakitcsi** [ajinasokan/flutter_curl#14]
I got error like the following image:
![image](https://github.com/user-attachments/assets/6b758733-2f3a-45e1-b204-155ae242be69)

_I don't know is it about the flutter version or not_ but I solved it by modifying the **_flutter_curl/android/build.gradle_** file with:
1. add 'namespace'
2. update 'minSdkVersion' from 16 to 21

![image](https://github.com/user-attachments/assets/9f25f8e7-dba0-4732-b04b-dd21072a6a53)

the reason I changed the 'minSdkVersion' because I had got a warning with some error about **deprecated sdk api**

Currently I have to do modify the **_flutter_curl/android/build.gradle_** file manually after 'flutter pub add flutter_curl'
Do you have  the better solution ?

**Comment by ajinasokan** [comment]
Sorry missed this.

I have done the necessary changes in the master. Possible to try it? You can use the latest master commit like below in pubpsec.
```
flutter_curl:
    git:
      url: https://github.com/ajinasokan/flutter_curl
      ref: 2771b30608d83c0ca53e66ab5693ac159a121904
```
